---
- name: Create EC2 Instance
  hosts: localhost
  gather_facts: False
#   collections:
#     - community.aws

  vars:
    region: "us-east-1"
    instance_type: "t2.micro"
    image_id: "ami-04a0ae173da5807d3"
    keypair: "svkey"
    security_group: "sg-09e9e77d2670971dc"
    subnet_id: "subnet-031e76e7270ef47f8"
    tag_name: "ansible-server"
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:
    - name: Create EC2 Instance
      ec2_instance:
        region: "{{ region }}"
        image_id: "{{ image_id }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ keypair }}"
        security_group: "{{ security_group }}"
        subnet_id: "{{ subnet_id }}"
        tags:
          Name: "{{ tag_name }}"
        wait: yes
      register: ec2_instance
 
    - name: print EC2 Instance Details
      debug:
        var: ec2_instance
